//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Generic;

namespace Foo.Bar.Commons
{
    /// <summary>
    /// Stores all the existing client rights
    /// </summary>
    public static partial class ClientRights
    {
        private static readonly List<string> all;
        private static readonly Dictionary<string, string> descriptions;

        #region Constructor

        /// <summary>
        /// Initializes the <see cref="ClientRights"/> class.
        /// </summary>
        static ClientRights()
        {
            all = new List<string>();
            descriptions = new Dictionary<string, string>();

            all.Add(FooBarSecurityPluginUsersManagement);
            descriptions.Add(FooBarSecurityPluginUsersManagement, FooBarSecurityPluginUsersManagementDescription);
            all.Add(FooBarSecurityPluginProfileManagement);
            descriptions.Add(FooBarSecurityPluginProfileManagement, FooBarSecurityPluginProfileManagementDescription);
            all.Add(FooBarSecurityPluginProfileAgentHistory);
            descriptions.Add(FooBarSecurityPluginProfileAgentHistory, FooBarSecurityPluginProfileAgentHistoryDescription);
            all.Add(FooBarDocumentPluginPackageAcknowledgement);
            descriptions.Add(FooBarDocumentPluginPackageAcknowledgement, FooBarDocumentPluginPackageAcknowledgementDescription);
            all.Add(FooBarIdentityPluginSearchForInspect);
            descriptions.Add(FooBarIdentityPluginSearchForInspect, FooBarIdentityPluginSearchForInspectDescription);
            all.Add(FooBarIdentityPluginValidation);
            descriptions.Add(FooBarIdentityPluginValidation, FooBarIdentityPluginValidationDescription);
            all.Add(FooBarApplicationPluginValidation);
            descriptions.Add(FooBarApplicationPluginValidation, FooBarApplicationPluginValidationDescription);
            all.Add(FooBarReportPluginReportManagement);
            descriptions.Add(FooBarReportPluginReportManagement, FooBarReportPluginReportManagementDescription);
            all.Add(FooBarReportPluginReportExport);
            descriptions.Add(FooBarReportPluginReportExport, FooBarReportPluginReportExportDescription);
            all.Add(FooBarApplicationPluginSearch);
            descriptions.Add(FooBarApplicationPluginSearch, FooBarApplicationPluginSearchDescription);
            all.Add(FooBarSupplyPluginStockView);
            descriptions.Add(FooBarSupplyPluginStockView, FooBarSupplyPluginStockViewDescription);
            all.Add(FooBarSupplyPluginStockManagement);
            descriptions.Add(FooBarSupplyPluginStockManagement, FooBarSupplyPluginStockManagementDescription);
            all.Add(FooBarAdministrationCertificatesManagement);
            descriptions.Add(FooBarAdministrationCertificatesManagement, FooBarAdministrationCertificatesManagementDescription);
            all.Add(FooBarAdministrationRedListManagement);
            descriptions.Add(FooBarAdministrationRedListManagement, FooBarAdministrationRedListManagementDescription);
            all.Add(FooBarDocumentsInvalidDocumentsManagement);
            descriptions.Add(FooBarDocumentsInvalidDocumentsManagement, FooBarDocumentsInvalidDocumentsManagementDescription);
            all.Add(FooBarMasterDataSupportingDocumentTypesManagement);
            descriptions.Add(FooBarMasterDataSupportingDocumentTypesManagement, FooBarMasterDataSupportingDocumentTypesManagementDescription);
            all.Add(FooBarMasterDataCitiesManagement);
            descriptions.Add(FooBarMasterDataCitiesManagement, FooBarMasterDataCitiesManagementDescription);
            all.Add(FooBarMasterDataCountriesManagement);
            descriptions.Add(FooBarMasterDataCountriesManagement, FooBarMasterDataCountriesManagementDescription);
            all.Add(FooBarMasterDataEyeColorsManagement);
            descriptions.Add(FooBarMasterDataEyeColorsManagement, FooBarMasterDataEyeColorsManagementDescription);
            all.Add(FooBarMasterDataMaritalStatusesManagement);
            descriptions.Add(FooBarMasterDataMaritalStatusesManagement, FooBarMasterDataMaritalStatusesManagementDescription);
            all.Add(FooBarMasterDataGenericDataManagement);
            descriptions.Add(FooBarMasterDataGenericDataManagement, FooBarMasterDataGenericDataManagementDescription);
            all.Add(FooBarMasterDataGenericDataByDocumentTypeManagement);
            descriptions.Add(FooBarMasterDataGenericDataByDocumentTypeManagement, FooBarMasterDataGenericDataByDocumentTypeManagementDescription);
            all.Add(FooBarMasterDataDocumentValidityDurationsManagement);
            descriptions.Add(FooBarMasterDataDocumentValidityDurationsManagement, FooBarMasterDataDocumentValidityDurationsManagementDescription);
            all.Add(FooBarMasterDataSitesManagement);
            descriptions.Add(FooBarMasterDataSitesManagement, FooBarMasterDataSitesManagementDescription);
            all.Add(FooBarMasterDataRejectedDocumentReasonsManagement);
            descriptions.Add(FooBarMasterDataRejectedDocumentReasonsManagement, FooBarMasterDataRejectedDocumentReasonsManagementDescription);
            all.Add(FooBarMasterDataRejectedApplicationReasonsManagement);
            descriptions.Add(FooBarMasterDataRejectedApplicationReasonsManagement, FooBarMasterDataRejectedApplicationReasonsManagementDescription);
            all.Add(FooBarMasterDataApplicationTypesManagement);
            descriptions.Add(FooBarMasterDataApplicationTypesManagement, FooBarMasterDataApplicationTypesManagementDescription);
            all.Add(FooBarMasterDataFaceAnalysisCriteriaManagement);
            descriptions.Add(FooBarMasterDataFaceAnalysisCriteriaManagement, FooBarMasterDataFaceAnalysisCriteriaManagementDescription);
            all.Add(FooBarDocumentPluginDuplicate);
            descriptions.Add(FooBarDocumentPluginDuplicate, FooBarDocumentPluginDuplicateDescription);
            all.Add(FooBarCashingPluginCashRegisterClosing);
            descriptions.Add(FooBarCashingPluginCashRegisterClosing, FooBarCashingPluginCashRegisterClosingDescription);
            all.Add(FooBarCashingPluginCashRegisterInitialization);
            descriptions.Add(FooBarCashingPluginCashRegisterInitialization, FooBarCashingPluginCashRegisterInitializationDescription);
            all.Add(FooBarCashingPluginCashRegisterManagement);
            descriptions.Add(FooBarCashingPluginCashRegisterManagement, FooBarCashingPluginCashRegisterManagementDescription);
            all.Add(FooBarCashingPluginCashRegisterSupervision);
            descriptions.Add(FooBarCashingPluginCashRegisterSupervision, FooBarCashingPluginCashRegisterSupervisionDescription);
            all.Add(FooBarCashingPluginDocumentRefund);
            descriptions.Add(FooBarCashingPluginDocumentRefund, FooBarCashingPluginDocumentRefundDescription);
            all.Add(FooBarCashingPluginDocumentPurchase);
            descriptions.Add(FooBarCashingPluginDocumentPurchase, FooBarCashingPluginDocumentPurchaseDescription);
            all.Add(FooBarCashingPluginInvoiceSearch);
            descriptions.Add(FooBarCashingPluginInvoiceSearch, FooBarCashingPluginInvoiceSearchDescription);
        }

        #endregion

        /// <summary>
        /// Gets all the defined client rights.
        /// </summary>
        public static string[] All
        {
            get { return all.ToArray(); }
        }

        /// <summary>
        /// Gets the description of the specified right.
        /// </summary>
        /// <param name="rightName">Name of the right.</param>
        /// <returns>The right description or an empty string.</returns>
        public static string GetDescription(string rightName)
        {
            if (descriptions.ContainsKey(rightName))
                return descriptions[rightName];
            return string.Empty;
        }

        #region Rights definitions

        /// <summary>
        /// When part of a user's principal roles, Users security management
        /// </summary>
        [Description(FooBarSecurityPluginUsersManagementDescription)]
        public const string FooBarSecurityPluginUsersManagement = "foo.bar.securityPlugin.usersManagement";
        private const string FooBarSecurityPluginUsersManagementDescription = "Users security management";

        /// <summary>
        /// When part of a user's principal roles, Security profile management
        /// </summary>
        [Description(FooBarSecurityPluginProfileManagementDescription)]
        public const string FooBarSecurityPluginProfileManagement = "foo.bar.securityPlugin.profileManagement";
        private const string FooBarSecurityPluginProfileManagementDescription = "Security profile management";

        /// <summary>
        /// When part of a user's principal roles, Profiles and users history
        /// </summary>
        [Description(FooBarSecurityPluginProfileAgentHistoryDescription)]
        public const string FooBarSecurityPluginProfileAgentHistory = "foo.bar.securityPlugin.profileAgentHistory";
        private const string FooBarSecurityPluginProfileAgentHistoryDescription = "Profiles and users history";

        /// <summary>
        /// When part of a user's principal roles, Package and document acknowledgement
        /// </summary>
        [Description(FooBarDocumentPluginPackageAcknowledgementDescription)]
        public const string FooBarDocumentPluginPackageAcknowledgement = "foo.bar.documentPlugin.packageAcknowledgement";
        private const string FooBarDocumentPluginPackageAcknowledgementDescription = "Package and document acknowledgement";

        /// <summary>
        /// When part of a user's principal roles, Search identity to inspect
        /// </summary>
        [Description(FooBarIdentityPluginSearchForInspectDescription)]
        public const string FooBarIdentityPluginSearchForInspect = "foo.bar.identityPlugin.searchForInspect";
        private const string FooBarIdentityPluginSearchForInspectDescription = "Search identity to inspect";

        /// <summary>
        /// When part of a user's principal roles, Identity validation
        /// </summary>
        [Description(FooBarIdentityPluginValidationDescription)]
        public const string FooBarIdentityPluginValidation = "foo.bar.identityPlugin.validation";
        private const string FooBarIdentityPluginValidationDescription = "Identity validation";

        /// <summary>
        /// When part of a user's principal roles, Application validation
        /// </summary>
        [Description(FooBarApplicationPluginValidationDescription)]
        public const string FooBarApplicationPluginValidation = "foo.bar.applicationPlugin.validation";
        private const string FooBarApplicationPluginValidationDescription = "Application validation";

        /// <summary>
        /// When part of a user's principal roles, Reports management
        /// </summary>
        [Description(FooBarReportPluginReportManagementDescription)]
        public const string FooBarReportPluginReportManagement = "foo.bar.reportPlugin.reportManagement";
        private const string FooBarReportPluginReportManagementDescription = "Reports management";

        /// <summary>
        /// When part of a user's principal roles, Reports export
        /// </summary>
        [Description(FooBarReportPluginReportExportDescription)]
        public const string FooBarReportPluginReportExport = "foo.bar.reportPlugin.reportExport";
        private const string FooBarReportPluginReportExportDescription = "Reports export";

        /// <summary>
        /// When part of a user's principal roles, Search application
        /// </summary>
        [Description(FooBarApplicationPluginSearchDescription)]
        public const string FooBarApplicationPluginSearch = "foo.bar.applicationPlugin.search";
        private const string FooBarApplicationPluginSearchDescription = "Search application";

        /// <summary>
        /// When part of a user's principal roles, Stock display
        /// </summary>
        [Description(FooBarSupplyPluginStockViewDescription)]
        public const string FooBarSupplyPluginStockView = "foo.bar.supplyPlugin.stock.view";
        private const string FooBarSupplyPluginStockViewDescription = "Stock display";

        /// <summary>
        /// When part of a user's principal roles, Stock management
        /// </summary>
        [Description(FooBarSupplyPluginStockManagementDescription)]
        public const string FooBarSupplyPluginStockManagement = "foo.bar.supplyPlugin.stock.management";
        private const string FooBarSupplyPluginStockManagementDescription = "Stock management";

        /// <summary>
        /// When part of a user's principal roles, Certificates management
        /// </summary>
        [Description(FooBarAdministrationCertificatesManagementDescription)]
        public const string FooBarAdministrationCertificatesManagement = "foo.bar.administration.certificatesManagement";
        private const string FooBarAdministrationCertificatesManagementDescription = "Certificates management";

        /// <summary>
        /// When part of a user's principal roles, Red list management
        /// </summary>
        [Description(FooBarAdministrationRedListManagementDescription)]
        public const string FooBarAdministrationRedListManagement = "foo.bar.administration.redListManagement";
        private const string FooBarAdministrationRedListManagementDescription = "Red list management";

        /// <summary>
        /// When part of a user's principal roles, Invalid documents management
        /// </summary>
        [Description(FooBarDocumentsInvalidDocumentsManagementDescription)]
        public const string FooBarDocumentsInvalidDocumentsManagement = "foo.bar.documents.invalidDocumentsManagement";
        private const string FooBarDocumentsInvalidDocumentsManagementDescription = "Invalid documents management";

        /// <summary>
        /// When part of a user's principal roles, Supporting document types management
        /// </summary>
        [Description(FooBarMasterDataSupportingDocumentTypesManagementDescription)]
        public const string FooBarMasterDataSupportingDocumentTypesManagement = "foo.bar.masterData.supportingDocumentTypesManagement";
        private const string FooBarMasterDataSupportingDocumentTypesManagementDescription = "Supporting document types management";

        /// <summary>
        /// When part of a user's principal roles, Cities management
        /// </summary>
        [Description(FooBarMasterDataCitiesManagementDescription)]
        public const string FooBarMasterDataCitiesManagement = "foo.bar.masterData.citiesManagement";
        private const string FooBarMasterDataCitiesManagementDescription = "Cities management";

        /// <summary>
        /// When part of a user's principal roles, Countries management
        /// </summary>
        [Description(FooBarMasterDataCountriesManagementDescription)]
        public const string FooBarMasterDataCountriesManagement = "foo.bar.masterData.countriesManagement";
        private const string FooBarMasterDataCountriesManagementDescription = "Countries management";

        /// <summary>
        /// When part of a user's principal roles, Eye colors management
        /// </summary>
        [Description(FooBarMasterDataEyeColorsManagementDescription)]
        public const string FooBarMasterDataEyeColorsManagement = "foo.bar.masterData.eyeColorsManagement";
        private const string FooBarMasterDataEyeColorsManagementDescription = "Eye colors management";

        /// <summary>
        /// When part of a user's principal roles, Marital statuses management
        /// </summary>
        [Description(FooBarMasterDataMaritalStatusesManagementDescription)]
        public const string FooBarMasterDataMaritalStatusesManagement = "foo.bar.masterData.maritalStatusesManagement";
        private const string FooBarMasterDataMaritalStatusesManagementDescription = "Marital statuses management";

        /// <summary>
        /// When part of a user's principal roles, Generic data management
        /// </summary>
        [Description(FooBarMasterDataGenericDataManagementDescription)]
        public const string FooBarMasterDataGenericDataManagement = "foo.bar.masterData.genericDataManagement";
        private const string FooBarMasterDataGenericDataManagementDescription = "Generic data management";

        /// <summary>
        /// When part of a user's principal roles, Generic data by document type management
        /// </summary>
        [Description(FooBarMasterDataGenericDataByDocumentTypeManagementDescription)]
        public const string FooBarMasterDataGenericDataByDocumentTypeManagement = "foo.bar.masterData.genericDataByDocumentTypeManagement";
        private const string FooBarMasterDataGenericDataByDocumentTypeManagementDescription = "Generic data by document type management";

        /// <summary>
        /// When part of a user's principal roles, Document validity durations management
        /// </summary>
        [Description(FooBarMasterDataDocumentValidityDurationsManagementDescription)]
        public const string FooBarMasterDataDocumentValidityDurationsManagement = "foo.bar.masterData.documentValidityDurationsManagement";
        private const string FooBarMasterDataDocumentValidityDurationsManagementDescription = "Document validity durations management";

        /// <summary>
        /// When part of a user's principal roles, Sites management
        /// </summary>
        [Description(FooBarMasterDataSitesManagementDescription)]
        public const string FooBarMasterDataSitesManagement = "foo.bar.masterData.sitesManagement";
        private const string FooBarMasterDataSitesManagementDescription = "Sites management";

        /// <summary>
        /// When part of a user's principal roles, Rejected document reasons management
        /// </summary>
        [Description(FooBarMasterDataRejectedDocumentReasonsManagementDescription)]
        public const string FooBarMasterDataRejectedDocumentReasonsManagement = "foo.bar.masterData.rejectedDocumentReasonsManagement";
        private const string FooBarMasterDataRejectedDocumentReasonsManagementDescription = "Rejected document reasons management";

        /// <summary>
        /// When part of a user's principal roles, Rejected application reasons management
        /// </summary>
        [Description(FooBarMasterDataRejectedApplicationReasonsManagementDescription)]
        public const string FooBarMasterDataRejectedApplicationReasonsManagement = "foo.bar.masterData.rejectedApplicationReasonsManagement";
        private const string FooBarMasterDataRejectedApplicationReasonsManagementDescription = "Rejected application reasons management";

        /// <summary>
        /// When part of a user's principal roles, Application types management
        /// </summary>
        [Description(FooBarMasterDataApplicationTypesManagementDescription)]
        public const string FooBarMasterDataApplicationTypesManagement = "foo.bar.masterData.applicationTypesManagement";
        private const string FooBarMasterDataApplicationTypesManagementDescription = "Application types management";

        /// <summary>
        /// When part of a user's principal roles, Face analysis criteria management
        /// </summary>
        [Description(FooBarMasterDataFaceAnalysisCriteriaManagementDescription)]
        public const string FooBarMasterDataFaceAnalysisCriteriaManagement = "foo.bar.masterData.faceAnalysisCriteriaManagement";
        private const string FooBarMasterDataFaceAnalysisCriteriaManagementDescription = "Face analysis criteria management";

        /// <summary>
        /// When part of a user's principal roles, Duplicate document
        /// </summary>
        [Description(FooBarDocumentPluginDuplicateDescription)]
        public const string FooBarDocumentPluginDuplicate = "foo.bar.documentPlugin.duplicate";
        private const string FooBarDocumentPluginDuplicateDescription = "Duplicate document";

        /// <summary>
        /// When part of a user's principal roles, Close cash registers
        /// </summary>
        [Description(FooBarCashingPluginCashRegisterClosingDescription)]
        public const string FooBarCashingPluginCashRegisterClosing = "foo.bar.cashingPlugin.cashRegisterClosing";
        private const string FooBarCashingPluginCashRegisterClosingDescription = "Close cash registers";

        /// <summary>
        /// When part of a user's principal roles, Initialize cash registers
        /// </summary>
        [Description(FooBarCashingPluginCashRegisterInitializationDescription)]
        public const string FooBarCashingPluginCashRegisterInitialization = "foo.bar.cashingPlugin.cashRegisterInitialization";
        private const string FooBarCashingPluginCashRegisterInitializationDescription = "Initialize cash registers";

        /// <summary>
        /// When part of a user's principal roles, Manage cash registers
        /// </summary>
        [Description(FooBarCashingPluginCashRegisterManagementDescription)]
        public const string FooBarCashingPluginCashRegisterManagement = "foo.bar.cashingPlugin.cashRegisterManagement";
        private const string FooBarCashingPluginCashRegisterManagementDescription = "Manage cash registers";

        /// <summary>
        /// When part of a user's principal roles, Supervise cash registers
        /// </summary>
        [Description(FooBarCashingPluginCashRegisterSupervisionDescription)]
        public const string FooBarCashingPluginCashRegisterSupervision = "foo.bar.cashingPlugin.cashRegisterSupervision";
        private const string FooBarCashingPluginCashRegisterSupervisionDescription = "Supervise cash registers";

        /// <summary>
        /// When part of a user's principal roles, Refund document
        /// </summary>
        [Description(FooBarCashingPluginDocumentRefundDescription)]
        public const string FooBarCashingPluginDocumentRefund = "foo.bar.cashingPlugin.documentRefund";
        private const string FooBarCashingPluginDocumentRefundDescription = "Refund document";

        /// <summary>
        /// When part of a user's principal roles, Sell document
        /// </summary>
        [Description(FooBarCashingPluginDocumentPurchaseDescription)]
        public const string FooBarCashingPluginDocumentPurchase = "foo.bar.cashingPlugin.documentPurchase";
        private const string FooBarCashingPluginDocumentPurchaseDescription = "Sell document";

        /// <summary>
        /// When part of a user's principal roles, Search invoices
        /// </summary>
        [Description(FooBarCashingPluginInvoiceSearchDescription)]
        public const string FooBarCashingPluginInvoiceSearch = "foo.bar.cashingPlugin.invoiceSearch";
        private const string FooBarCashingPluginInvoiceSearchDescription = "Search invoices";

        #endregion
    }
}